### ISSUE TITLE
Potter: update wfd blobs

### ISSUE THREAD

**Issue by anuraag488** [DirtyUnicorns/android_vendor_motorola#2]
@flintman currently WFD crashes. On arrowos wfd working.
This commit needs merging i think.
https://github.com/ArrowOS-Devices/android_vendor_motorola_potter/commit/2bfed265706b43a4e8232020eaddd4f57ba47a98

**Comment by BoredOutOfMyGit** [comment]
Report issues on JIRA

https://jira.dirtyunicorns.com/
